#!/usr/bin/env zsh
#
# Generate favicon files

fav_svg='./favicon.svg'
touch_icon_svg='./apple-touch-icon.svg' 
ico_sizes=('16' '32' '48' '57' '64' '96' '128' '192' '196')
fav_pub='./images/magick'

rm $fav_pub/*.png
rm $fav_pub/*.ico
rm $fav_pub/*.svg

for size in $ico_sizes; do
    magick -background none $fav_svg -resize "${size}x${size}" "favicon-${size}.png"
done

# create favicon.ico
magick favicon-16.png favicon-32.png favicon-64.png favicon.ico

touch_sizes=('57' '76' '120' '152' '180' '192')

for size in $touch_sizes; do
    magick -background none $touch_icon_svg -resize "${size}x${size}" "apple-touch-icon-${size}x${size}.png"
done

magick -background none $touch_icon_svg -resize "180x180" "apple-touch-icon.png"

test -d $fav_pub || mkdir $fav_pub
mv *.ico *.png "$fav_pub/"
cp $fav_svg "$fav_pub/"
